git clone -b $GIT_BRANCH https://$GITHUB_TOKEN\@github.com/skalenetwork/skale-node.git

cd ./skale-node/installation
DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD RUN_MODE=admin RPC_IP=$RPC_IP RPC_PORT=$RPC_PORT \
    DB_USER=$DB_USER DB_PASSWORD=$DB_PASS CUSTOM_CONTRACTS=true sudo -E bash install.sh



GIT_BRANCH=
GITHUB_TOKEN=
DOCKER_USERNAME=
DOCKER_PASSWORD=
RPC_IP=
RPC_PORT=
DB_USER=
DB_PASSWORD=