[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "node-cli"
version = "3.2.0"
description = "Node CLI tools"
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }
keywords = ["skale", "cli"]
authors = [{ name = "SKALE Labs", email = "support@skalelabs.com" }]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU Affero General Public License v3",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.13",
]

dependencies = [
  "click==8.3.1",
  "distro==1.9.0",
  "docker==7.1.0",
  "texttable==1.7.0",
  "python-dateutil==2.9.0.post0",
  "Jinja2==3.1.6",
  "psutil==7.1.3",
  "python-dotenv==1.2.1",
  "terminaltables==3.1.10",
  "requests==2.32.5",
  "GitPython==3.1.45",
  "packaging==25.0",
  "python-debian==1.0.1",
  "PyYAML==6.0.3",
  "pyOpenSSL==25.3.0",
  "MarkupSafe==3.0.3",
  "Flask==3.1.2",
  "itsdangerous==2.2.0",
  "cryptography==46.0.5",
  "filelock==3.20.0",
  "sh==2.2.2",
  "python-crontab==3.3.0",
  "requests-mock==1.12.1",
  "redis==7.1.1",
  "PyInstaller==6.18.0",
  "skale.py-core==7.13.dev4",
]

[project.urls]
Homepage = "https://github.com/skalenetwork/node-cli"

[project.optional-dependencies]
dev = [
  "ruff==0.14.6",
  "bumpversion==0.6.0",
  "pytest==9.0.1",
  "pytest-cov==7.0.0",
  "twine==6.2.0",
  "mock==5.2.0",
  "freezegun==1.5.5",
]

[tool.setuptools]
package-dir = { "" = "." }
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.format]
quote-style = "single"

[tool.uv]
prerelease = "allow"


[tool.pytest.ini_options]
log_cli = false
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
filterwarnings = ["ignore::DeprecationWarning"]
