[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "node-cli"
version = "3.2.0"
description = "Node CLI tools"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
keywords = ["skale", "cli"]
authors = [
  { name = "SKALE Labs", email = "support@skalelabs.com" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.11",
]

dependencies = [
  "click==8.1.7",
  "distro==1.9.0",
  "docker==6.0.1",
  "texttable==1.6.7",
  "python-dateutil==2.8.2",
  "Jinja2==3.1.4",
  "psutil==5.9.4",
  "python-dotenv==0.21.0",
  "terminaltables==3.1.10",
  "requests==2.28.1",
  "GitPython==3.1.41",
  "packaging==23.0",
  "python-debian==0.1.49",
  "PyYAML==6.0.3",
  "pyOpenSSL==24.2.1",
  "MarkupSafe==3.0.2",
  "Flask==2.3.3",
  "itsdangerous==2.1.2",
  "cryptography==42.0.4",
  "filelock==3.0.12",
  "sh==1.14.2",
  "python-crontab==2.6.0",
  "requests-mock==1.12.1",
  "redis==6.2.0",
]

[project.urls]
Homepage = "https://github.com/skalenetwork/node-cli"

[project.optional-dependencies]
dev = [
  "ruff==0.14.0",
  "bumpversion==0.6.0",
  "pytest==8.4.2",
  "pytest-cov==7.0.0",
  "twine==4.0.2",
  "mock==4.0.3",
  "freezegun==1.5.5",
  "PyInstaller>=6.14.0",
]

[tool.setuptools]
package-dir = { "" = "." }
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py311"
