#   -*- coding: utf-8 -*-
#
#   This file is part of node-cli
#
#   Copyright (C) 2019 SKALE Labs
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.


import logging

from node_cli.core.nftables import (
    LEGACY_CHAIN,
    LEGACY_FAMILY,
    LEGACY_TABLE,
    POLICY,
    NFTablesManager,
    remove_legacy_saved_rules
)
from node_cli.utils.helper import run_cmd

logger = logging.getLogger(__name__)


ALLOWED_INCOMING_TCP_PORTS = [
    '80',  # filestorage
    '311',  # watchdog https
    '8080',  # http
    '443',  # https
    '53',  # dns
    '3009',  # watchdog http
    '9100'  # node exporter
]

ALLOWED_INCOMING_UDP_PORTS = [
    '53'  # dns
]


class NFTablesCmdFailedError(Exception):
    pass


def remove_tcp_rules() -> None:
    tcp_rule_template = 'iptables -{} {} -p tcp -m tcp --dport {} -j ACCEPT'
    for tcp_port in [*ALLOWED_INCOMING_TCP_PORTS]:
        check_cmd = tcp_rule_template.format('C', LEGACY_CHAIN, tcp_port).split(' ')
        remove_cmd = tcp_rule_template.format('D', LEGACY_CHAIN, tcp_port).split(' ')
        result = run_cmd(check_cmd, check_code=False)
        if result.returncode == 0:
            result = run_cmd(remove_cmd)


def remove_udp_rules() -> None:
    udp_rule_template = 'iptables -{} {} -p udp -m udp --dport {} -j ACCEPT'
    for udp_port in [*ALLOWED_INCOMING_UDP_PORTS]:
        check_cmd = udp_rule_template.format('C', LEGACY_CHAIN, udp_port).split(' ')
        remove_cmd = udp_rule_template.format('D', LEGACY_CHAIN, udp_port).split(' ')
        result = run_cmd(check_cmd, check_code=False)
        if result.returncode == 0:
            result = run_cmd(remove_cmd)


def remove_loopback_rules() -> None:
    loopback_rule_template = 'iptables -{} {} -i lo -j ACCEPT'
    check_cmd = loopback_rule_template.format('C', LEGACY_CHAIN).split(' ')
    remove_cmd = loopback_rule_template.format('D', LEGACY_CHAIN).split(' ')
    result = run_cmd(check_cmd, check_code=False)
    if result.returncode == 0:
        result = run_cmd(remove_cmd)


def remove_icmp_rules() -> None:
    icmp_rule_template = 'iptables -{} {} -p icmp -m icmp --icmp-type {} -j ACCEPT'
    for icmp_type in [3, 4, 11]:
        check_cmd = icmp_rule_template.format('C', LEGACY_CHAIN, icmp_type).split(' ')
        remove_cmd = icmp_rule_template.format('D', LEGACY_CHAIN, icmp_type).split(' ')
        result = run_cmd(check_cmd, check_code=False)
        if result.returncode == 0:
            result = run_cmd(remove_cmd)


def remove_conntrack_rules() -> None:
    track_rule_template = 'iptables -{} {} -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT'
    check_cmd = track_rule_template.format('C', LEGACY_CHAIN).split(' ')
    remove_cmd = track_rule_template.format('D', LEGACY_CHAIN).split(' ')
    result = run_cmd(check_cmd, check_code=False)
    if result.returncode == 0:
        result = run_cmd(remove_cmd)


def remove_drop_rules() -> None:
    drop_rule_template = 'iptables -{} {} -p {} -j DROP'
    protocols = ['tcp', 'udp']
    for proto in protocols:
        check_cmd = drop_rule_template.format('C', LEGACY_CHAIN, proto).split(' ')
        remove_cmd = drop_rule_template.format('D', LEGACY_CHAIN, proto).split(' ')
        result = run_cmd(check_cmd, check_code=False)
        if result.returncode == 0:
            result = run_cmd(remove_cmd)


def remove_old_iptables_rules() -> None:
    remove_drop_rules()
    remove_conntrack_rules()
    remove_loopback_rules()
    remove_tcp_rules()
    remove_icmp_rules()


def migrate() -> None:
    nft = NFTablesManager(family=LEGACY_FAMILY, table=LEGACY_TABLE, chain=LEGACY_CHAIN)
    logger.info('Making sure legacy chain has default policy accept')
    nft.update_chain_policy(chain=LEGACY_CHAIN, policy=POLICY)

    logger.info('Running migration from focal to jammy')
    remove_old_iptables_rules()

    logger.info('Flushing nftables rules generated by release upgrade')
    nft.cleanup_rules(ssh=False, dns=False)

    # Logging rules after migration
    res = run_cmd(['nft', 'list', 'ruleset'])
    plain_rules = res.stdout.decode('utf-8')
    logger.debug(plain_rules)

    remove_legacy_saved_rules()

    logger.info('Migration from focal to jammy completed')
