name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python-setuptools
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -e .[dev]
        pip install --upgrade 'setuptools<45.0.0'
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Build binary
      run: |
        docker build . -t node-cli-builder
        mkdir ./dist
        docker run  -v /home/ubuntu/dist:/app/dist node-cli-builder scripts/build.sh test test
    - name: Check build
      run: /home/ubuntu/dist/skale-test-Linux-x86_64
    - name: Run tests
      run: bash ./scripts/run_tests.sh
