name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Checkout submodules
      run: git submodule update --init

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}

    - name: Install ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install iptables nftables python3-nftables

    - name: Install python dependencies
      run: |
        uv pip install -e ".[dev]"

    - name: Generate info
      run: bash ./scripts/generate_info.sh 1.0.0 my-branch skale

    - name: Check with ruff
      run: |
        ruff check

    - name: Build binary - skale
      run: |
        mkdir -p ./dist
        docker build . -t node-cli-builder
        docker run  -v /home/ubuntu/dist:/app/dist node-cli-builder bash scripts/build.sh test test skale
        docker rm -f $(docker ps -aq)

    - name: Check build - skale
      run: sudo /home/ubuntu/dist/skale-test-Linux-x86_64

    - name: Build binary - fair
      run: |
        mkdir -p ./dist
        docker build . -t node-cli-builder
        docker run  -v /home/ubuntu/dist:/app/dist node-cli-builder bash scripts/build.sh test test fair
        docker rm -f $(docker ps -aq)

    - name: Check build - fair
      run: sudo /home/ubuntu/dist/skale-test-Linux-x86_64-fair

    - name: Run prepare test build
      run: |
        bash scripts/build.sh test test skale

    - name: Run redis
      run: |
        bash ./helper-scripts/redis/run.sh

    - name: Run tests
      run: |
        export PYTHONPATH=${PYTHONPATH}:/usr/lib/python3/dist-packages/
        bash ./scripts/run_tests.sh

    - name: Run nftables tests
      run: |
        scripts/run_nftables_test.sh
